name: Python Test Module

on:
  workflow_call:
    inputs:
      service_path:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install & Test
        working-directory: ${{ inputs.service_path }}
        run: |
          pip install -r requirements.txt
          pip install pytest
          if [ -d "tests" ]; then
            pytest
          else
            echo "No tests found, running syntax check..."
            python -m py_compile main.py
          fi
